### ISSUE TITLE
Please provide a git tag that points to the latest stable version

### ISSUE THREAD

**Issue by dundargoc** [zeebe-io/backport-action#280]
It's possible to choose the latest commit by just specifying the main branch, but it'd be nice to have a way to point to the latest stable version. The official github actions does this by manually moving their `v1`, `v2`, `v3`... tags to point to the latest stable versions ([example](https://github.com/actions/checkout/tags)). Another common way to do this is to use the git tag `latest` if one doesn't want to mess with multiple versions.

**Comment by korthout** [comment]
Hi @dundargoc 👋 I was on holiday for a few weeks, so it took me some time to reply to this. Anyways, thanks for reporting. 

I've tried to read up on the topic. Although moving git tags is [controversial](https://github.com/actions/toolkit/issues/214), it seems to be the [official way to do versioning](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md). 

I think it should also be easy to do (although it's some extra manual work for me 😅), doesn't block users from referencing exact versions or commit sha's, and I think it solves an actual problem. So, I'll tag the current latest release as `v0`.

I hope that one day this can be handled [automatically](https://github.com/orgs/community/discussions/9847).

**Comment by korthout** [comment]
I've introduced a `v0` [tag](https://github.com/zeebe-io/backport-action/tags), and updated the installation examples in the README.

**Comment by dundargoc** [comment]
Thank you, I truly appreciate this and the work you do.
