### ISSUE TITLE
Node.js 12 deprecation

### ISSUE THREAD

**Issue by mweinelt** [zeebe-io/backport-action#288]
We're seeing the following warnings on our backport actions. I assume this is something in the action itself, so reposting it here:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: zeebe-io/backport-action

**Comment by korthout** [comment]
Thanks for raising this @mweinelt 🙌 

This must be completed before Summer 2023, but I plan to update it before that.

>We plan to migrate all actions to run on Node16 by Summer 2023

**Comment by korthout** [comment]
Fixed with #295

**Comment by basefas** [comment]
@korthout need a new release to put it into effect, thanks.

**Comment by korthout** [comment]
I've released https://github.com/zeebe-io/backport-action/releases/tag/v0.0.9
