### ISSUE TITLE
backport label regex

### ISSUE THREAD

**Issue by domenkozar** [zeebe-io/backport-action#36]
It would be useful to be able to configure the label name with a regex that extracts the branch name:

```yml
backport_label_pattern: '^backport-to-(.*)$'
```

**Comment by korthout** [comment]
Hi @domenkozar, glad to see you're using the bot 👍 

I sounds like a useful feature. Let me make sure I understand what you mean: the label name pattern is currently hard coded to match the regex `^backport ([^ ]+)?$`, and you'd like to make this pattern configurable. 

Note that in the pattern `^backport ([^ ]+)?$` a space is not an allowed as branchname character, while it is allowed in github labels. see https://regex101.com/r/pS1wzb/1

I guess we should restrict somehow what these patterns are supposed to look like to make configuration easy. Tthere must be only 1 capture group that captures branchname compliant strings. For this, we could consider a special identifier or a keyword to match a branchname and allow the rest of the label pattern to be customized. For example, an identifier like `${branchname}`. Let's say you then configure `backport_label_pattern: 'foo-${branchname}-bar'` which would result in a regex pattern `^foo-([^ ]+)?-bar$`, that can match labels like `foo-1.0.0-bar` and then capture `1.0.0` as branchname. 

It's a bit complex, but this at least makes sure no wrong configurations can be provided. How do you feel about this solution and would it solve your case?

**Comment by domenkozar** [comment]
I'd keep it simple and flexible by using regex and then check there's only one capture group.

Why do you forbid the space (I don't need that, just wondering), it could be just `^backport (.+)$`?

**Comment by pihme** [comment]
I would also keep it simple and iterate from there.

**Comment by korthout** [comment]
>I'd keep it simple and flexible by using regex

Sounds good, we can always extend it later if the need is there. For now, I agree that we can start by making it configurable.

>Why do you forbid the space

A branchname cannot contain a space, so it would just fail creating the branch. Failure could be fine too, but at the time we chose to just not execute the backporting logic for such labels.

**Comment by korthout** [comment]
@domenkozar I've just released a new version (v0.0.4) that adds support for a custom label pattern. See #42 for details. Please let me know if you run into any problems.
