### ISSUE TITLE
Placeholders for the original PR author, and user that made the label or comment

### ISSUE THREAD

**Issue by nh2** [zeebe-io/backport-action#75]
I would like to automatically subscribe to the backport PR by `@`-mentioning them:

* the user who attached the label (or wrote the `/backport` comment) that triggered the backport PR
* the author of the original, non-backport PR

The new `pull_description` functionality from PR #64 by @korthout is perfect for that, but we would need [placeholder variables](https://github.com/zeebe-io/backport-action/tree/2b994724142df0774855690db56bc6308fb99ffa#placeholders) for those two users.

**Comment by korthout** [comment]
@nh2 Sounds like a great addition! I'm almost done finishing up a pull request for #29 by adding a new placeholder `${issue_refs}`. And I 

For the author of the original pull, I think something like `${pull_author}` would be fitting.

For the other type of user, I'm not sure. Perhaps `${sender}` (matching the GitHub naming) or `${triggered_by}` (feels a bit more in the action's domain). Do you have any suggestions or preferences?

**Comment by nh2** [comment]
> For the author of the original pull, I think something like `${pull_author}` would be fitting.

Yes sounds good, or `${original_pull_author}` if we want to be super specific.

> Perhaps `${sender}` (matching the GitHub naming) or `${triggered_by}`

How about `${backport_trigger_user}`?

Also I think the docs of such feature should then explain whether the placeholder already contains the `@`, or not -- for example, would "triggered by @${backport_trigger_user}` `@`-mention them?

**Comment by korthout** [comment]
@nh2 Thanks for the suggestions! I'll have to think a bit about what I like best for naming.

I totally agree with the `@` character. Leaving it out is more flexible. I'll make sure the doc is clear on what the placeholder is replaced with.

**Comment by korthout** [comment]
Hi @nh2. I've added the `pull_author` placeholder. You can prefix it with an `@` character like this: `@${pull_author}` to mention the user and subscribe them to notifications for the newly created backport pull request.

Note that I have not yet released a new version officially, but you can just refer to latest commit on `main`: 4c106a22b132961ec31097db8035bb849a401471.

Let me know if you run into any issues.
